login: 
    path: /login
    defaults:  {_controller: AppBundle:User:login}
login_check:
    path: /login_check
logout:
    path: /logout
register:
    path: /register
    defaults: {_controller: AppBundle:User:register}
comprobar_nick_usuario:
    path: /comprobarUsuario
    defaults: {_controller: AppBundle:User:comprobarNick}
    methods: [POST]
comprobar_correo_usuario:
    path: /comprobarCorreo
    defaults: {_controller: AppBundle:User:comprobarCorreo}
    methods: [POST]
user_config:
    path: /user-config
    defaults: {_controller: AppBundle:User:editUser}
user_list:
    path: /people
    defaults: {_controller: AppBundle:User:users}
user_search:
    path: /search
    defaults: {_controller: AppBundle:User:search}
user_perfil:
    path: /user/{usernick}
    defaults: {_controller: AppBundle:User:perfil, usernick:null}





    
    
