BackendBundle\Entity\Alerts:
    type: entity
    table: alerts
    indexes:
        fk_alerts_users_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        notiType:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: noti_type
        notiTypeId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: noti_type_id
        isReaded:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: is_readed
        creationDate:
            type: datetime
            nullable: true
            column: creation_date
        misscellaneous:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
